
#
#spring.profiles.active=test
#


server:
  port: 10005

spring:
  application:
    name: file
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql.show: true
    datasource:
      names: master,slave0,slave1
      common:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.10:3306/win-help?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
        username: root
        password: ws101122..
        type: com.zaxxer.hikari.HikariDataSource
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.10:3306/win-help?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
        username: root
        password: ws101122..
        type: com.zaxxer.hikari.HikariDataSource
      slave0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.10:3306/win-help?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
        username: root
        password: ws101122..
        type: com.zaxxer.hikari.HikariDataSource
      slave1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.10:3306/win-help?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
        username: root
        password: ws101122..
        type: com.zaxxer.hikari.HikariDataSource
    rules:
      replica-query:
        data-sources:
          master:
            primary-date-source: master
            replica-date-source-names: slave0,slave1
            load-balance-name: round-robin
        load-balances:
          round-robin:
            type: ROUND_ROBIN
            props:
              workId: 1
#


mybatis-plus:
  mapper-locations: classpath*:xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/


